---
title: "Plots"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r settings, echo=F, message=F, results='hide', warning = F, eval = T}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, cache = F, fig = TRUE, global.par = TRUE, dev = 'pdf')
#, dev = 'pdf'
options(width  = 100)
options(scipen = 999)
        
# Load libraries
library(data.table)
library(ggplot2)
library(reshape2)
library(dplyr)
library(GGally)
library(PerformanceAnalytics)
library(mlbench)
library(caret)
library(glmnet)
library(Hmisc)
library(randomForest)
library(discretization)
# Make sure functions from dplyr are acting as functions from dplyr 
filter    <- dplyr::filter
mutate    <- dplyr::mutate
group_by  <- dplyr::group_by
summarize <- dplyr::summarize
select    <- dplyr::select

# Define project directory path 

```

```{r aa, echo=F, message=F, results='hide', warning = F, cache = F}
setwd('path to \\Figures\\Figure2\\data')

#############################################################################################
library(Hmisc)
library(dplyr)
library(ggplot2)

#------------------------------------------------------------------------------------

k      <- matrix(c(3, 25, 50, 75, 100, 125, 150, 175, 200, 225, 250), 11, 1);
yMAX   <- 0.15;
iter   <- 300;
q1     <- 0.05;
q2     <- 0.1;

name1  <- "q = 0.05"
name2  <- "q = 0.1"
 
pch1   <- 16;
pch2   <- 17;

lty0   <- 1;
lty1   <- 2;
lty2   <- 2;

color0 <- "black";
col1   <- "red";
col2   <- "blue";

fdr1   <- read.table("FDR_005_ORTa.txt");
al1    <- as.numeric(fdr1);
al1    <- as.matrix(al1);
fdr1   <- al1;

s1     <- read.table("stdFDR_005_ORTa.txt");
sl1    <- as.numeric(s1);
sl1    <- as.matrix(sl1);
s1     <- sl1/sqrt(iter);

fdr2   <- read.table("FDR_01_ORTa.txt");
al1    <- as.numeric(fdr2);
al1    <- as.matrix(al1);
fdr2   <- al1;

s2     <- read.table("stdFDR_01_ORTa.txt");
sl2    <- as.numeric(s2);
sl2    <- as.matrix(sl2);
s2     <- sl2/sqrt(iter);

names  <- c(name2, name1);
colors <- c(col2, col1);
pchs   <- c(pch2, pch1);
ltys   <- c(lty2, lty1);

#=======================================================================
estim    <- rbind(fdr1, fdr2)
se       <- rbind(s1, s2)
lower    <- estim - 2*se
upper    <- estim + 2*se
names    <- c(rep("q = 0.05", times = length(k)), rep("q = 0.1", times = length(k)))
sparsity <- rep(k,times = 2)

#--------------------------------------
df       <- data.frame("gFDR"= estim, "lower"=lower, "upper"=upper, sparsity, names)
#--------------------------------------

xbeg  <-  k[1] - 8
xend  <-  k[length(k)] + 8
ybeg  <-  0.05*(1000 - k[1])/1000
yend  <-  0.05*(1000 - k[length(k)])/1000
ybeg2 <-  0.1*(1000 - k[1])/1000
yend2 <-  0.1*(1000 - k[length(k)])/1000

p <- ggplot(df, aes(sparsity, gFDR, colour= names))
p <- p + geom_segment(mapping = aes(x = xbeg, y = ybeg, xend = xend, yend = yend), linetype = 2, color = "black", size = 0.5)
p <- p + geom_segment(mapping = aes(x = xbeg, y = ybeg2, xend = xend, yend = yend2), linetype = 2, color = "black", size = 0.5)
p <- p + geom_line(mapping = aes(x = sparsity, y = gFDR, color = names), size = 1)
p <- p + scale_color_manual(values=c("chartreuse3", "chartreuse3"))
p <- p + scale_shape_manual(values = c(17,16))
p <- p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 5) 
p <- p + geom_point(df, mapping=aes(x = sparsity, y = gFDR, shape = names), size = 8)
p <- p + coord_cartesian( xlim = c(k[1],  k[length(k)]),  ylim = c(0, 0.13) )
p <- p + labs(title="", x = 'Number of relevant groups', y = 'Estimated gFDR', color = "target gFDR", shape = "target gFDR")
p <- p + theme_bw(base_size = 35)
p <- p + theme( legend.position = c(.95, .95), legend.justification = c("right", "top"), legend.box.background = element_rect())
p <- p + theme(legend.text=element_text(size=35))
p <- p + theme(legend.title = element_blank())
p <- p + theme(legend.key.size =  unit(.5, "in"))
p <- p + theme(legend.key = element_rect(size = 15))
#p <- p + theme(plot.background = element_rect(fill = 'grey98', colour = 'black'))
p <- p + theme(legend.background = element_rect(colour = 'black'))

```

```{r figure2a, fig.width=10, fig.height=9.5, cache = F}
plot(p)
```



```{r bb, echo=F, message=F, results='hide', warning = F, cache = F}
setwd('path to \\Figures\\Figure2\\data')

#############################################################################################
library(Hmisc)
library(dplyr)
library(ggplot2)

#------------------------------------------------------------------------------------

k      <- matrix(c(3, 25, 50, 75, 100, 125, 150, 175, 200, 225, 250), 11, 1);
yMAX   <- 0.15;
iter   <- 300;
q1     <- 0.05;
q2     <- 0.1;

name1  <- "q = 0.05"
name2  <- "q = 0.1"
 
pch1   <- 16;
pch2   <- 17;

lty0   <- 1;
lty1   <- 2;
lty2   <- 2;

color0 <- "black";
col1   <- "red";
col2   <- "blue";

fdr1  <- read.table("FDR_005_MAX_WEAK.txt");
al1   <- as.numeric(fdr1);
al1   <- as.matrix(al1);
fdr1  <- al1;

s1    <- read.table("stdFDR_005_MAX_WEAK.txt");
sl1   <- as.numeric(s1);
sl1   <- as.matrix(sl1);
s1    <- sl1/sqrt(iter);

fdr2  <- read.table("FDR_01_MAX_WEAK.txt");
al1   <- as.numeric(fdr2);
al1   <- as.matrix(al1);
fdr2  <- al1;

s2    <- read.table("stdFDR_01_MAX_WEAK.txt");
sl2   <- as.numeric(s2);
sl2   <- as.matrix(sl2);
s2    <- sl2/sqrt(iter);

names  <- c(name2, name1);
colors <- c(col2, col1);
pchs   <- c(pch2, pch1);
ltys   <- c(lty2, lty1);

#=======================================================================
estim    <- rbind(fdr1, fdr2)
se       <- rbind(s1, s2)
lower    <- estim - 2*se
upper    <- estim + 2*se
names    <- c(rep("q = 0.05", times = length(k)), rep("q = 0.1", times = length(k)))
sparsity <- rep(k,times = 2)

#--------------------------------------
df       <- data.frame("gFDR"= estim, "lower"=lower, "upper"=upper, sparsity, names)
#--------------------------------------

xbeg  <-  k[1] - 8
xend  <-  k[length(k)] + 8
ybeg  <-  0.05*(1000 - k[1])/1000
yend  <-  0.05*(1000 - k[length(k)])/1000
ybeg2 <-  0.1*(1000 - k[1])/1000
yend2 <-  0.1*(1000 - k[length(k)])/1000

p <- ggplot(df, aes(sparsity, gFDR, colour= names))
p <- p + geom_segment(mapping = aes(x = xbeg, y = ybeg, xend = xend, yend = yend), linetype = 2, color = "black", size = 0.5)
p <- p + geom_segment(mapping = aes(x = xbeg, y = ybeg2, xend = xend, yend = yend2), linetype = 2, color = "black", size = 0.5)
p <- p + geom_line(mapping = aes(x = sparsity, y = gFDR, color = names), size = 1.1)
p <- p + scale_color_manual(values=c("red", "red"))
p <- p + scale_shape_manual(values = c(17,16))
p <- p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 5) 
p <- p + geom_point(df, mapping=aes(x = sparsity, y = gFDR, shape = names), size = 8)
p <- p + coord_cartesian( xlim = c(k[1],  k[length(k)]),  ylim = c(0, 0.13) )
p <- p + labs(title="", x = 'Number of relevant groups', y = 'Estimated gFDR', color = "target gFDR", shape = "target gFDR")
p <- p + theme_bw(base_size = 35)
p <- p + theme( legend.position = c(.95, .95), legend.justification = c("right", "top"), legend.box.background = element_rect())
p <- p + theme(legend.text=element_text(size=35))
p <- p + theme(legend.title = element_blank())
p <- p + theme(legend.key.size =  unit(.5, "in"))
#p <- p + theme(plot.background = element_rect(fill = 'grey98', colour = 'black'))
p <- p + theme(legend.background = element_rect(colour = 'black'))
```

```{r figure2b, fig.width=10, fig.height=9.5, cache = F}
plot(p)
```

```{r cc, echo=F, message=F, results='hide', warning = F, cache = F}
setwd('path to \\Figures\\Figure2\\data')

#############################################################################################
library(Hmisc)
library(dplyr)
library(ggplot2)

#------------------------------------------------------------------------------------

k      <- matrix(c(3, 25, 50, 75, 100, 125, 150, 175, 200, 225, 250), 11, 1);
yMAX   <- 0.15;
iter   <- 300;
q1     <- 0.05;
q2     <- 0.1;

name1  <- "q = 0.05"
name2  <- "q = 0.1"
 
pch1   <- 16;
pch2   <- 17;

lty0   <- 1;
lty1   <- 2;
lty2   <- 2;

color0 <- "black";
col1   <- "red";
col2   <- "blue";

fdr1   <- read.table("FDR_005_MEAN_WEAK.txt");
al1    <- as.numeric(fdr1);
al1    <- as.matrix(al1);
fdr1   <- al1;

s1     <- read.table("stdFDR_005_MEAN_WEAK.txt");
sl1    <- as.numeric(s1);
sl1    <- as.matrix(sl1);
s1     <- sl1/sqrt(iter);

fdr2   <- read.table("FDR_01_MEAN_WEAK.txt");
al1    <- as.numeric(fdr2);
al1    <- as.matrix(al1);
fdr2   <- al1;

s2     <- read.table("stdFDR_01_MEAN_WEAK.txt");
sl2    <- as.numeric(s2);
sl2    <- as.matrix(sl2);
s2     <- sl2/sqrt(iter);

names  <- c(name2, name1);
colors <- c(col2, col1);
pchs   <- c(pch2, pch1);
ltys   <- c(lty2, lty1);

#=======================================================================

estim    <- rbind(fdr1, fdr2)
se       <- rbind(s1, s2)
lower    <- estim - 2*se
upper    <- estim + 2*se
names    <- c(rep("q = 0.05", times = length(k)), rep("q = 0.1", times = length(k)))
sparsity <- rep(k,times = 2)

#--------------------------------------
df       <- data.frame("gFDR"= estim, "lower"=lower, "upper"=upper, sparsity, names)
#--------------------------------------

xbeg  <-  k[1] - 8
xend  <-  k[length(k)] + 8
ybeg  <-  0.05*(1000 - k[1])/1000
yend  <-  0.05*(1000 - k[length(k)])/1000
ybeg2 <-  0.1*(1000 - k[1])/1000
yend2 <-  0.1*(1000 - k[length(k)])/1000

p <- ggplot(df, aes(sparsity, gFDR, colour= names))
p <- p + geom_segment(mapping = aes(x = xbeg, y = ybeg, xend = xend, yend = yend), linetype = 2, color = "black", size = 0.6)
p <- p + geom_segment(mapping = aes(x = xbeg, y = ybeg2, xend = xend, yend = yend2), linetype = 2, color = "black", size = 0.6)
p <- p + geom_line(mapping = aes(x = sparsity, y = gFDR, color = names), size = 1.1)
p <- p + scale_color_manual(values=c("blue", "blue"))
p <- p + scale_shape_manual(values = c(17,16))
p <- p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 5) 
p <- p + geom_point(df, mapping=aes(x = sparsity, y = gFDR, shape = names), size = 9)
p <- p + coord_cartesian( xlim = c(k[1],  k[length(k)]),  ylim = c(0, 0.13) )
p <- p + labs(title="", x = 'Number of relevant groups', y = 'Estimated gFDR', color = "target gFDR", shape = "target gFDR")
p <- p + theme_bw(base_size = 35)
p <- p + theme( legend.position = c(.95, .95), legend.justification = c("right", "top"), legend.box.background = element_rect())
p <- p + theme(legend.text=element_text(size=35))
p <- p + theme(legend.title = element_blank())
p <- p + theme(legend.key.size =  unit(.5, "in"))
#p <- p + theme(plot.background = element_rect(fill = 'grey98', colour = 'black'))
p <- p + theme(legend.background = element_rect(colour = 'black'))

```

```{r figure2c, fig.width=10, fig.height = 9.5, cache = F}
plot(p)
```



```{r dd, echo=F, message=F, results='hide', warning = F, cache = F}
setwd('path to \\Figures\\Figure2\\data')

#############################################################################################
library(Hmisc)
library(dplyr)
library(ggplot2)

#------------------------------------------------------------------------------------

k      <- matrix(c(3, 25, 50, 75, 100, 125, 150, 175, 200, 225, 250), 11, 1);
yMAX   <- 0.15;
iter   <- 300;
q1     <- 0.05;
q2     <- 0.1;

name1  <- "q = 0.05"
name2  <- "q = 0.1"
 
pch1   <- 16;
pch2   <- 17;

lty0   <- 1;
lty1   <- 2;
lty2   <- 2;

color0 <- "black";
col1   <- "red";
col2   <- "blue";

pow1  <- read.table("POWER_005_MAX_WEAK.txt");
al1   <- as.numeric(pow1);
al1   <- as.matrix(al1);
pow1  <- al1;

pow2  <- read.table("POWER_01_MAX_WEAK.txt");
al1   <- as.numeric(pow2);
al1   <- as.matrix(al1);
pow2  <- al1;

pow3  <- read.table("POWER_005_MEAN_WEAK.txt");
al1   <- as.numeric(pow3);
al1   <- as.matrix(al1);
pow3  <- al1;

pow4  <- read.table("POWER_01_MEAN_WEAK.txt");
al1   <- as.numeric(pow4);
al1   <- as.matrix(al1);
pow4  <- al1;


#=======================================================================
estim    <- rbind(pow1, pow2, pow3, pow4)
names    <- c(rep("q = 0.05,", times = length(k)), rep("q = 0.1,", times = length(k)), rep("q = 0.05,", times = length(k)), rep("q = 0.1,", times = length(k)))
names2   <- c(rep("lambda_max", times = 2*length(k)), rep("lambda_mean", times = 2*length(k)))
names3   <- paste(names, names2)
sparsity <- rep(k, times = 4)

#--------------------------------------
df       <- data.frame("gFDR"= estim, sparsity, names3)
df$names3 <- factor(as.character(df$names3), levels = c("q = 0.05, lambda_max",  "q = 0.1, lambda_max", "q = 0.05, lambda_mean", "q = 0.1, lambda_mean"))

#--------------------------------------

xbeg  <-  k[1] - 8
xend  <-  k[length(k)] + 8
ybeg  <-  0.05*(1000 - k[1])/1000
yend  <-  0.05*(1000 - k[length(k)])/1000
ybeg2 <-  0.1*(1000 - k[1])/1000
yend2 <-  0.1*(1000 - k[length(k)])/1000


p <- ggplot(df, aes(sparsity, gFDR, colour= names3))
p <- p + geom_line(mapping = aes(x = sparsity, y = gFDR, color = names3), size = 1.1)
p <- p + geom_point(df, mapping=aes(x = sparsity, y = gFDR, shape = names3), size = 8)
p <- p + scale_color_manual(values=c("red", "red", "blue","blue"), labels = expression(paste("q = 0.05,  ", lambda^ "max"), paste("q = 0.1,   ", lambda^ "max"), paste("q = 0.05, ", lambda^ "mean"), paste("q = 0.1,  ", lambda^ "mean")))
p <- p + scale_shape_manual(values = c(17, 16, 17, 16), labels = expression(paste("q = 0.05,  ", lambda^ "max"), paste("q = 0.1,   ", lambda^ "max"), paste("q = 0.05, ", lambda^ "mean"), paste("q = 0.1,  ", lambda^ "mean")))
p <- p + labs(title="", x = 'Number of relevant groups', y = 'Estimated power', color = "target gFDR", shape = "target gFDR")
p <- p + theme_bw(base_size = 35)
p <- p + theme( legend.position = c(.95, .05), legend.justification = c("right", "bottom"), legend.box.background = element_rect())
p <- p + theme(legend.text=element_text(size=35))
p <- p + theme(legend.title = element_blank())
p <- p + theme(legend.key.size =  unit(.5, "in"))
p <- p + theme(legend.background = element_rect(colour = 'black'))

```


```{r figure2d, fig.width=10, fig.height=9.5, cache = F}
plot(p)
```




```{r ee, echo=F, message=F, results='hide', warning = F, cache = F}
setwd('path to \\Figures\\Figure2\\data')

#############################################################################################
library(Hmisc)
library(dplyr)
library(ggplot2)

#------------------------------------------------------------------------------------

max_lam_idx <- 500;
yMAX        <- 0.15;
q1          <- 0.05;
q2          <- 0.1;

#------------------------------------------------------------------------------------

lambda_q1_mean <- as.matrix(as.numeric(read.table("lambda_q1_mean.txt", row.names = NULL)));
lambda_q2_mean <- as.matrix(as.numeric(read.table("lambda_q2_mean.txt", row.names = NULL)));
lambda_q1_max  <- as.matrix(as.numeric(read.table("lambda_q1_max.txt", row.names = NULL)));
lambda_q2_max  <- as.matrix(as.numeric(read.table("lambda_q2_max.txt", row.names = NULL)));

lambda_q1_mean <- lambda_q1_mean[1:max_lam_idx]
lambda_q2_mean <- lambda_q2_mean[1:max_lam_idx]
lambda_q1_max  <- lambda_q1_max[1:max_lam_idx]
lambda_q2_max  <- lambda_q2_max[1:max_lam_idx]

lambdas  <- c(lambda_q1_max, lambda_q2_max, lambda_q1_mean, lambda_q2_mean)
idxs     <- rep(1:max_lam_idx, times = 4)
names    <- c(rep("lambda_q1_max", times = max_lam_idx), rep("lambda_q2_max", times = max_lam_idx), rep("lambda_q1_mean", times = max_lam_idx), rep("lambda_q2_mean", times = max_lam_idx))
df       <- data.frame(lambdas, idxs, names)
df$names <- factor(as.character(df$names), levels =  c("lambda_q1_max", "lambda_q2_max", "lambda_q1_mean",  "lambda_q2_mean"))



p <- ggplot(df, aes(idxs, lambdas, colour= names))
p <- p + geom_line(mapping = aes(idxs, lambdas, colour= names, linetype = names), size = 1.1)
p <- p + scale_linetype_manual(values = c(2,1,2,1),  labels = expression(paste("q = 0.05,  ", lambda^ "max"), paste("q = 0.1,   ", lambda^ "max"), paste("q = 0.05, ", lambda^ "mean"), paste("q = 0.1,  ", lambda^ "mean")))
p <- p + scale_color_manual(values=c("red", "red", "blue","blue"), labels = expression(paste("q = 0.05,  ", lambda^ "max"), paste("q = 0.1,   ", lambda^ "max"), paste("q = 0.05, ", lambda^ "mean"), paste("q = 0.1,  ", lambda^ "mean")))
p <- p + labs(title="", x = 'Index', y = 'Value', color = "target gFDR", linetype = "target gFDR")
p <- p + theme_bw(base_size = 35)
p <- p + theme( legend.position = c(.95, .95), legend.justification = c("right", "top"), legend.box.background = element_rect())
p <- p + theme(legend.text=element_text(size=35))
p <- p + theme(legend.title = element_blank())
p <- p + theme(legend.key.size =  unit(.5, "in"))
#p <- p + theme(plot.background = element_rect(fill = 'grey98', colour = 'black'))
p <- p + theme(legend.background = element_rect(colour = 'black'))

```

```{r figure2e, fig.width=10, fig.height=9.5, cache = F}
plot(p)
```



<!-- plots could be found in \\Figures2_files\\figure-html\\ directory -->


